spec:
  name: karma-volunteer-platform
  services:
    - name: api
      github:
        repo: jshimas/karma-volunteer-platform
        branch: main
        deploy_on_push: true
      source_dir: karma-api
      dockerfile_path: karma-api/Dockerfile
      routes:
        - path: /karma-api
