services:
  db:
    image: postgres:15.3
    container_name: psq_karma_db
    environment:
      POSTGRES_DB: karma_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:  