spring:
  datasource:
    url: jdbc:postgresql://db:5432/karma_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  flyway:
    enabled: true

jwt:
  secret:
    key: 5n/a5etrP2kt6MxenBELZ3sSVuz6SFiPuHgOXpJiuc8=
  expiration:
    access: 600000  # 10 minutes
    refresh: 2592000000  # 30 days




