spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOSTNAME}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  flyway:
    enabled: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  expiration:
    access: 600000  # 10 minutes
    refresh: 2592000000  # 30 days